export default {
  SPLASH_WITH_SEARCH: 'SPLASH WITH SEARCH',
  TAB_BAR_HOME: 'TAB_BAR_HOME',
  INVENTORY: 'Inventory',
  SELL_US: 'Sell us',
  ABOUT_US: 'About Us',
  CONTACT: 'Contact',
  FACEBOOK: 'Facebook',
  HOME: 'Home',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  PRODUCT_DETAIL: 'Product Detail',
  FILTER: 'Filter',
  LOGIN: 'Login',
  SIGN_UP: 'Sign Up',
  VERIFY_OTP: 'Verify OTP',
  CREATE_TOKEN: 'Create Token',
  NOTIFICATIONS: 'Notifications',
  ADD_PRODUCT: 'Add Product',
  APP_UPDATE: 'Gursevak App Updates',
  DOWNLOAD_RESOURCE: 'Download Sources',
};
