import { Dimensions, Platform } from 'react-native';

export const WINDOW_DEVICE_WIDTH = Dimensions.get('window').width;
export const WINDOW_DEVICE_HEIGHT = Dimensions.get('window').height;
export const IS_IOS = Platform.OS === 'ios';
export const SHIFT_ID = 'SHIFT_ID';
export const LATITUDE = 'LATITUDE';
export const LONGITUDE = 'LONGITUDE';
export const CURRENT_TIME = 'CURRENT_TIME';
export const CHECKPOINT_ID = 'CHECKPOINT_ID'
export const MODE_TYPE = 'MODE_TYPE'
export const ACCOUNTS = 'accounts'

export const  data = [
    {
        id:0,
        title:'ਓ',
        height:'18%'
    },
    {
        id:1,
        title:'ਅ',
        height:'18%'
    },
    {
        id:2,
        title:'ੲ',
        height:'18%'
    },
    {
        id:3,
        title:'ਸ',
        height:'18%'
    },
    {
        id:4,
        title:'ਹ',
        height:'18%'
    },
    {
        id:5,
        title:'ਕ',
        height:'18%'
    },
    {
        id:6,
        title:'ਖ',
        height:'18%'
    },
    {
        id:7,
        title:'ਗ',
        height:'18%'
    },
    {
        id:8,
        title:'ਘ',
        height:'18%'
    },
    {
        id:9,
        title:'ਙ',
        height:'18%'
    },
    {
        id:10,
        title:'ਚ',
        height:'18%'
    },
    {
        id:11,
        title:'ਛ',
        height:'18%'
    },
    {
        id:12,
        title:'ਜ',
        height:'18%'
    },
    {
        id:13,
        title:'ਝ',
        height:'18%'
    },
    {
        id:14,
        title:'ਞ',
        height:'18%'
    },
    {
        id:15,
        title:'ਟ',
        height:'18%'
    },
    {
        id:16,
        title:'ਠ',
        height:'18%'
    },
    {
        id:17,
        title:'ਡ',
        height:'18%'
    },
    {
        id:18,
        title:'ਢ',
        height:'18%'
    },
    {
        id:19,
        title:'ਣ',
        height:'18%'
    },
    {
        id:20,
        title:'ਤ',
        height:'18%'
    },
    {
        id:21,
        title:'ਥ',
        height:'18%'
    },
    {
        id:22,
        title:'ਦ',
        height:'18%'
    },
    {
        id:23,
        title:'ਧ',
        height:'18%'
    },
    {
        id:24,
        title:'ਨ',
        height:'18%'
    },
    {
        id:25,
        title:'ਪ',
        height:'18%'
    },
    {
        id:26,
        title:'ਫ',
        height:'18%'
    },
    {
        id:27,
        title:'ਬ',
        height:'18%'
    },
    {
        id:28,
        title:'ਭ',
        height:'18%'
    },
    {
        id:29,
        title:'ਮ',
        height:'18%'
    },
    {
        id:30,
        title:'ਯ',
        height:'18%'
    },
    {
        id:31,
        title:'ਰ',
        height:'18%'
    },
    {
        id:32,
        title:'ਲ',
        height:'18%'
    },
    {
        id:33,
        title:'ਵ',
        height:'18%'
    },
    {
        id:34,
        title:'ੜ',
        height:'18%'
    },
    
]